name: GitHub Actions Demo
on: [push, pull_request]
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    concurrency: 
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Pwd
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        if: github.base_ref != 'master' 
        run: |
          pwd 
          echo "base_ref: $GITHUB_BASE_REF"
          echo "head_ref: $GITHUB_REF"
          echo "$GITHUB_CONTEXT"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Sleep 5
        run: sleep 5
      - name: Show current head
        run: git rev-parse HEAD
      - name: Install project dependencies
        run: go mod tidy
      - name: Test
        run: go test
